### ISSUE TITLE
Add a package.json to install development dependencies

### ISSUE THREAD

**Issue by johnyanarella** [CC-Archived/SWFService#5]
Only necessary for developers who want to build and test customizations to SWFService, but good to include as a step towards continuous integration (CI) and automated testing for this library (as discussed in #4).

`devDependencies` should reference:
- karma
- karma-mocha
- bower

**Comment by ThomasBurleson** [comment]
I think general best practice is to install project node_modules relative to project (not global)
-  npm and bower are globally installed (obviously)
-  bower items are installed local in **./bower_components**, 
-  npm items are local in **./node_modules**

**Comment by johnyanarella** [comment]
Agreed.

Introducing a `package.json` file will ensure these node dependencies are 1) identified and 2) easily installed locally to `./node_modules`

Thinking about this further - this also means I should be including the CoffeeScript compiler in the package.json's `devDependencies` as well.

There might be an argument for installing bower locally as well, given the changes they've made (and will likely continue to make) as that project has matured (ex. changing from `component.json` to `bower.json`, etc.)
